### ISSUE TITLE
vue3分支重构todo

### ISSUE THREAD

**Issue by birdmanmandbir** [tzfun/vue-web-terminal#20]
## Todo
- [x] vue-cli, webpack -> vite
- [x] js -> ts
- [x] 打包导出ts类型
- [x] 选项式api -> 组合式api
- [x] 左上角全屏按钮点击体验优化（当前点击范围不够大，只有点中心才生效；放大后再次点击，无法恢复之前大小）
- [x] 去除python编译脚本，替换为bash、js等
- [ ] 默认状态下输入不在可输入范围内的命令，会直接卡死, 应改为报错?
- [x] 清理==null判空
- [ ] json 下拉框无法选择（由于绑定了最外层的click事件）
- [x] 考虑去除codemirror和highlightjs依赖
- [x] header slot 恢复支持
- [x] eslint告警清理
- [x] demo和组件通过monorepo方式管理(pnpm workspace)
- [ ] demo js -> ts
- [x] demo调试时支持加载sourcemap
- [x] external dep(外部依赖)配置
- [x] demo 拖动 -> 改为vueuse实现
- [x] demo code显示问题
- [x] demo 拖动后点击，自动回到中央
- [x] vue-json-viewer替换为vue3-json-viewer
- [ ] vue3-json-viewer的深度参数似乎不生效， 待确认
- [ ] demo各用例拆分，方便单独调试
- [ ] 减少模板ref使用，替换为组件
- [x] focus失效
- [ ] 点标题为啥会自动回中央？
- [ ] flash的进度条太长
- [ ] 发布npm仓测试
- [ ] 重构commandstore, 移除lodash依赖
- [ ] 重新组织目录结构
- [ ] TerminalObj相关逻辑参考naive-ui用hooks等方式重构

## 暂时无法实现
- 导出的类型是否可带上文档（tsdoc）(vue-tsc当前不支持👎)

**Comment by tzfun** [comment]
感谢贡献👍  当你看到源码的时候应该不难看出，我对前端的模块设计、代码等不是很规范，毕竟非前端专业选手，感谢大佬改造，改造过程中有细节方面需要沟通可以加我微信。

**Comment by birdmanmandbir** [comment]
> 感谢贡献👍 当你看到源码的时候应该不难看出，我对前端的模块设计、代码等不是很规范，毕竟非前端专业选手，感谢大佬改造，改造过程中有细节方面需要沟通可以加我微信。

嗯, 其实我也刚做一年多哈哈,
改造过程中碰到vite的一个坑, 昨天才把demo跑起来, 预计这周搞定

你微信号是多少呀

**Comment by birdmanmandbir** [comment]
碰到个打包结果里有`import require$$0 from "vue";`导致报错的问题, 排查了半天是vue-json-viewer里面vue3引入有问题
不应该用`import Vue from "vue"`
原来不是vite的坑
我看看json-viewer能不能换成别的库吧

**Comment by tzfun** [comment]
> 你微信号是多少呀
README里面有写 `beifeng-tz`

**Comment by tzfun** [comment]
> 碰到个打包结果里有`import require$$0 from "vue";`导致报错的问题, 排查了半天是vue-json-viewer里面vue3引入有问题 不应该用`import Vue from "vue"` 原来不是vite的坑 我看看json-viewer能不能换成别的库吧

嗯嗯 这个库我也有计划替换掉，之前想自己做一个，无奈一直没时间

**Comment by birdmanmandbir** [comment]
全屏为什么要判断_isSafari? 我看edge也是有问题的, 是不是直接不判断就好了 @tzfun 
![image](https://user-images.githubusercontent.com/48193000/209158173-c5ae88f4-6881-4f33-b5ca-217765fa5b93.png)

**Comment by tzfun** [comment]
> 全屏为什么要判断_isSafari? 我看edge也是有问题的, 是不是直接不判断就好了 @tzfun 

实测下来Safari浏览器的全屏功能不太兼容，需要单独处理

**Comment by birdmanmandbir** [comment]
todo已迁移到pr中维护
